# Use the official Node.js image as the base image
FROM node:alpine

# Set the working directory
WORKDIR /frontend

# Copy package.json and package-lock.json to the container
COPY package.json ./

# Install project dependencies
RUN yarn install

COPY . .

# Expose the port your Nuxt app will run on
EXPOSE 3000 24678

# Start the Nuxt development server
CMD ["yarn", "dev"]