# Use the official Node.js image as the base image
FROM node:alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json ./

# Install project dependencies
RUN yarn install

COPY . .

# Expose the port your Nuxt app will run on
EXPOSE 80

# Start the Nuxt production server
CMD ["yarn", "start"]